name: Build Example Apps

on: 
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build: 
    name: "Build Example App"
    runs-on: macos-13
    strategy:
      max-parallel: 2
      matrix:
        project: [
          { scheme: 'Co-Badged Cards Example', path: 'Co-Badged Cards/SwiftUI/Co-Badged Cards Example.xcodeproj' }
        ]
    steps:
      - name: Cancel previous jobs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Git - Checkout
        uses: actions/checkout@v3.6.0
        with:
          ref: ${{ github.ref }}
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.0'
      - uses: ruby/setup-ruby@v1.171.0
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Build with fastlane
        run: |
          bundle exec fastlane ios build_example_app "scheme:${{ matrix.project.scheme }}" "project_path:${{ matrix.project.path }}"